### ISSUE TITLE
Suggestion for simplifying @transformative

### ISSUE THREAD

**Issue by pablisco** [serras/kopykat#2]
I've been thinking about the API surface for `@transformative`. Using `tranform()` feels a bit distant to the stdlib `copy()`.

We could potentially define a copy that takes transform operations with a postfix (like `As`), like:

```kotlin
data class Person(val name: String, val age: Int)

person.copy(
  ageAs = { it + 1 },
  nameAs = { it + " Extra" }
)
```
We could potentially generate permutations like:

```kotlin
fun Person.copy(ageAs: (Int) -> Int, nameAs: (String) -> String)
fun Person.copy(ageAs: (Int) -> Int)
fun Person.copy(nameAs: (String) -> String)
fun Person.copy(age: Int, nameAs: (String) -> String)
fun Person.copy(ageAs: (Int) -> Int, name: String)
```

Note: I thought about using defaults with both transformers and values, but that would make it not clear which one is applied. Open to suggestions though.

This would allow combining direct assignment and inline transformation. We can also add collection mutation as part of these too. 

What do you think @serras? 🙂 

PS: This could be a separate ticket, but we should consider having a single annotation for all use cases (maybe with plugin configuration to skip generating one or another)

**Comment by serras** [comment]
I would really prefer not generating permutations. I heard from the Arrow guys that their binary already exploded for all the variations for partial applications, and these would be potentially more.

In addition, you can always set to a value (instead of transforming) by using `field = { newValue }`, which I think is a pretty good compromise.

But agree that `transform` may be a bit odd as function name. What about `copyWith` or `copyMap`?

**Comment by serras** [comment]
We should also investigate whether `copy` would work well with respect to type checking. Maybe they can all share the same name!

**Comment by pablisco** [comment]
Yeah, permutation may add extra sie to the generation. About names, we may be able to provide options to override the defaults when applying transformative to a project and per annotation usage.

**Comment by serras** [comment]
@pablisco what do you think about `copyWith` as a replacement for `transform`?

**Comment by pablisco** [comment]
Hmm, with already has some meaning as part of Kotlin Scope functions: `with(scope) {}`

What about `copyMap`? A bit in line with flatMap. We `map` and then `copy`. As opposed to map and flatten.

**Comment by serras** [comment]
> Hmm, with already has some meaning as part of Kotlin Scope functions: `with(scope) {}`

I was inspired by functions like [`sortWith`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/sort-with.html) or [`associateWith`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/associate-with.html) with work like their counterparts without `With`, but take an additional functional argument.

> What about `copyMap`? A bit in line with flatMap. We `map` and then `copy`. As opposed to map and flatten.

That sounds good too.
