### ISSUE TITLE
Sealed hierarchy transformations

### ISSUE THREAD

**Issue by pablisco** [serras/kopykat#4]
An everyday use case for sealed classes and interfaces is to define states (for UI or otherwise).

We could support making transformations of such structures with a conditional copy function:

```kotlin
seales interface ViewState {
  object Loading : ViewState
  data class Content(val message: String) : ViewState
  data class Failure(val error: String) : ViewState
}

// gen
fun ViewState.copy( // or transform
  onLoading: (Loading) -> ViewState = { it },
  onContent: (Content) -> ViewState = { it },
  onFailure: (Failure) -> ViewState = { it },
) = ...
```

This makes it easier to mutate the state of a FSM when a transition happens.

**Comment by serras** [comment]
I have two comments about this. The first one is that whereas the new versions of `copy` are direct improvements, this can be easily done with `when` + `is`. In the latter case, you have the additional ability to reorder the branches, and use `else` if you need to handle only one case in a special way. In summary, I’m a bit on the fence over the utility of this.

Now, if we were to implement this, I would suggest to add an additional argument: 

```kotlin
defaultCase: ((ViewState) -> ViewState) = { it }
```

and make all the arguments optional. The ida would be that:
- if the case for what you get as argument is non-null, apply it
- otherwise apply `defaultCase`

**Comment by pablisco** [comment]
I need to think of a solid use case. There are some interesting options that may make this more appealing.

I forgot to make the content and failure mutable in my example. 

```kotlin
viewState.copy(
  onContent = { 
    message = message + " extra details"
  }
)
```

However, this means there is no transition, just a copy 

The option to omit cases could be handy though.

As for nullable, this can be done like `viewState.copy() ?: defaultCase()`. Additionally, we probably don't have a parameter for the default if we want to implement it. It could be a separate extension:

```kotlin
fun ViewState?.copy(...,
  onContent: ...,
  onLoading: ...,
  onFailure: ..., 
  orElse : () -> ViewState,
) : ViewState =
  this?.copy(...) ?: orElse()
```

There could also be an option to share a property on the sealed class/interface. In which case, having a MutableViewModel could be interesting.

Let's put this one on the back burner, value classes are more interesting now. And I need to think about this one a bit more.

**Comment by pablisco** [comment]
At the very least we could create copy/transform for the extensions. There is an option to get subclasses wth ksp. I'll create a separate ticket.

**Comment by pablisco** [comment]
Ok, I think I found a good use case for this. Sharing properties across sealed cases.

```kotlin
sealed interface ViewState {
  
  val query: Query
  
  data class Loading(override val query: Query) : ViewState
  data class Content(override val query: Query, val message: String) : ViewState
  data class Failure(override val query: Query, val error: String) : ViewState
}
```

So, in addition of each data class having it's own copy options. We could have a copy for either of them:

```kotlin
viewState.copy { query = Query("new search") }
```

Internally we can do something like:

```
when(viewState) {
  is Loading -> copy(block)
  is Content -> copy(block)
  is Failure -> copy(block)
}
```

This way we can mutate something across multiple types...

**Comment by nomisRev** [comment]
> Sharing properties across sealed cases.

That is an important use-case, but I see it as a different use-case as `Prism`.
Afaik in Haskell this works because it generates a `Lens<ViewState, Query>`, and in our case we could generate `copy` for a `sealed class` (or `interface`) _if_ all _cases_ are `data class`.

I'm not sure yet if I have a strong opinion about `Prism` yet. As @serras mentioned using `when` or `is` offers some pretty good solutions already. In combination with something like `copyNotNull` analog to `mapNotNull` you already get some decent syntax.

```kotlin
seales interface ViewState {
  object Loading : ViewState
  data class Content(val message: String) : ViewState
  data class Failure(val error: String) : ViewState
}

val x: ViewState = TODO()

fun main() {
  x.copyNotNull { 
    it.takeIf { it is Content }?.copy { message = message.toUpperCase() }
  }
}
```

**Comment by pablisco** [comment]
Hmm, does that takeIf work? I always tend to create a reified castAs() to do that as I thought that didn't work, although inference and contracts are getting really good.

I like the idea of copyNotNull, although it will only work with sealed classes. The data class copy block returns Unit.

**Comment by serras** [comment]
I think @pablisco's suggestion of adding `copy` and `copyMap` for the intersection of fields in all data classes inheriting the interface is spot on. In fact, for this we could generate the (1) mutable `copy`, (2) `copyMap`, and (3) a regular `copy`, which is not generated by the Kotlin compiler.

I am not sure what exactly the proposal with `copyNotNull` is... 🤔

**Comment by pablisco** [comment]
Actually, we wouldn't need to create `copyNotNull` . If we make the transform field operations accept a nullable return, we can ignore it by returning null. We can still provide the current behaviour.

I'll look into this after nested copies :crossed\_fingers: I think we have a plan :slightly\_smiling\_face:

**Comment by nomisRev** [comment]
> If we make the transform field operations accept a nullable return, we can ignore it by returning null

Can I still put _null_ as a value for `x: Int?` where `x = -1`? Or in other words can you _erase_ a value by using _copy_?

> I think @pablisco's suggestion of adding copy and copyMap for the intersection of fields in all data classes inheriting the interface is spot on.

Okay, I see. That solves _part_ of the problem only, no? If I understand correctly `copyMap` would only allow me to _map_ values of my current _case_, but would not allow me to _change_ the _case_.

> I am not sure what exactly the proposal with copyNotNull is... 🤔

`mapNotNull` or `copyNotNull` works as `filterMap` so it allows to go from `A` to `B`.

```kotlin
fun ViewState.setContentOnlyIfLoading(content: String): ViewState =
 copyNotNull { it.takeIf { it is Loading }?.let { Content(content) } }
```

**Comment by serras** [comment]
> Actually, we wouldn't need to create `copyNotNull` . If we make the transform field operations accept a nullable return, we can ignore it by returning null. We can still provide the current behaviour.

I'm not sure I like that. I think one of the advantages of KopyKat is that it's straightforward, just a couple additional methods, but with a simple behavior. If we start adding more complex behavior, then it loses that benefit.

For example, the code above could be rewritten as:

```kotlin
x.takeIf { it is Content }?.copy { message = message.toUpperCase() } ?: x
```

**Comment by nomisRev** [comment]
You're absolutely right. I was already editing my comment while you already replied.

**Comment by pablisco** [comment]
One positive of having copyMap accept null returns is that we can mix properties that change and those that can't:

```kotlin
data class Player(
  position: Pair<Int, Int>,
  collisions: List<Player>,
)

player.copyMap(
  position = { 
    (it + movement).takeIf { it.isInBounds() }
  },
  collisions = { calculateCollisions() },
)

```

Although, it's quite a rare edge case, so I wouldn't push too much for this.
